public Class ARApexClass
{
public Account createAccount(String name)  //method to create account
{
//Demo for RBI Team for large implementation
//More changes here as well
Account acc112 = new Account();
acc112.Name = name;
Contact con=new Contact();
Opportunity opp = new Opportunity();
Contract ctr = new Contract();
return acc112;
//Demo for VeriMatrix Team
//More changes here as well
}

public void testingAR(){

}
}